sonar.verbose=true
sonar.organization=sandy01
sonar.prjectKey=sandy01-key
sonar.projectName=sandymytrend
sonar.language=java
sonar.sourceEncoding=UTF-8
sonar.sources=.
sonar.java.binaries=target/classes
sonar.coverage.jacoco.xmlReportPath=target/site/jococo/jococo.xml
